import {test,expect} from '@playwright/test';
const ready=async page=>{await page.goto('/');await page.waitForFunction(()=>window.__gw?.ready);};
const barcode={name:'barcode-dogfood',weight:1.2,layers:[{id:'bars',name:'Bars',paint:'fill',node:{op:'union',children:[{name:'Thin bar',shape:'rect',x:4,y:3,w:1.2,h:18,r:.6},{name:'Wide bar',shape:'rect',x:8,y:3,w:2.4,h:18,r:1.2}]}},{id:'peer',name:'Peer stroke',paint:'stroke',node:{shape:'line',x1:17,y1:3,x2:17,y2:21}}]};
async function setup(page){await ready(page);await page.evaluate(async glyph=>{await window.__gw.importLibraryText(JSON.stringify([glyph]),'dogfood.json','replace');},barcode);}
const actions=async page=>{await page.getByRole('menuitem',{name:'Actions',exact:true}).click();};
test('Layers and canvas share gray/blue Actions; thin bar recovers single centerline with local width, Undo/reload/export preserve source',async({page})=>{
 await setup(page);const before=await page.evaluate(()=>JSON.stringify(window.__gw.S.glyph.layers));await page.locator('[data-tree-key="0:0"]').click({button:'right'});await actions(page);await page.locator('#itemMenu').screenshot({path:'artifacts/actions-menu.png'});const item=page.getByRole('menuitem',{name:'Create centerline',exact:true});await expect(item).toBeVisible();await expect(item.locator('svg')).toHaveAttribute('aria-hidden','true');await item.click();const dialog=page.getByRole('dialog',{name:'Create centerline',exact:true});await expect(dialog).toBeVisible();await dialog.screenshot({path:'artifacts/centerline-review.png'});await expect(page.getByLabel('Centerline method')).toHaveValue('bar');expect(Number(await page.getByLabel('Centerline stroke').inputValue())).toBeCloseTo(1.2,5);await page.getByLabel('Centerline stroke').fill('1.8');await page.getByLabel('Centerline stroke').press('Tab');await page.getByRole('button',{name:'Add centerline layer',exact:true}).click();await expect(dialog).not.toBeVisible();
 expect(await page.evaluate(()=>JSON.stringify(window.__gw.S.glyph.layers.slice(0,2)))).toBe(before);expect(await page.evaluate(()=>window.__gw.S.glyph.layers[2].strokeWidth)).toBe(1.8);expect(await page.evaluate(()=>window.__gw.S.glyph.layers[2].node.children.length)).toBe(1);await expect(page.locator('#gLayers path[stroke-width="1.8"]')).toHaveCount(1);await expect(page.locator('.lib-item[data-name="barcode-dogfood"] .library-customized')).toBeVisible();
 await page.locator('#undoBtn').click();expect(await page.evaluate(()=>window.__gw.S.glyph.layers.length)).toBe(2);await page.locator('#redoBtn').click();await page.evaluate(()=>window.__gw.flushSaves());await page.reload();await page.waitForFunction(()=>window.__gw?.ready);await expect(page.locator('#gLayers path[stroke-width="1.8"]')).toHaveCount(1);expect(await page.evaluate(()=>window.__gw.core.toSVG(window.__gw.S.glyph,{mode:'baked'}))).toContain('stroke-width="1.8"');
 await page.evaluate(()=>{const w=window.__gw;w.S.sel=[{l:0,p:[1]}];w.refresh(true);});await page.locator('#canvas').press('Shift+F10');await actions(page);await page.getByRole('menuitem',{name:'Create centerline',exact:true}).click();await page.getByRole('button',{name:'Cancel',exact:true}).click();
});
test('layer library toggles capture local values, show customized markers and allow rejoining tokens with Undo',async({page})=>{
 await setup(page);await page.locator('[data-tree-key="1:layer"]').click({button:'right'});const width=page.getByRole('menuitemcheckbox',{name:'Follow library thickness',exact:true});await expect(width).toHaveAttribute('aria-checked','true');await width.click();await page.locator('[data-tree-key="1:layer"]').click({button:'right'});await page.getByRole('menuitemcheckbox',{name:'Follow library rounding',exact:true}).click();await expect(page.locator('[data-tree-key="1:layer"] .customized-mark')).toBeVisible();
 await page.locator('#setThicknessEnabled').check();await page.locator('#setThickness').fill('2');await page.locator('#setThickness').press('Tab');await page.locator('#setRoundingEnabled').check();await page.locator('#setRounding').fill('1');await page.locator('#setRounding').press('Tab');expect(await page.evaluate(()=>window.__gw.S.glyph.layers[1].strokeWidth)).toBe(1.2);await expect(page.locator('#gLayers path[stroke-width="1.2"]')).toHaveCount(1);await expect(page.locator('#gLayers [data-stroke-tip]')).toHaveCount(0);
 await page.locator('[data-tree-key="1:layer"]').click({button:'right'});await width.click();await expect(page.locator('#gLayers path[stroke-width="2"]')).toHaveCount(1);await page.locator('#undoBtn').click();await expect(page.locator('#gLayers path[stroke-width="1.2"]')).toHaveCount(1);
});
test('Actions keyboard entry and Escape return focus; invalid inset cannot publish and canceled review leaves source unchanged',async({page})=>{
 await setup(page);await page.locator('[data-tree-key="0:0"]').click({button:'right'});const button=page.getByRole('menuitem',{name:'Actions',exact:true});await button.focus();await page.keyboard.press('ArrowRight');await expect(page.locator('#selectionActions')).toBeVisible();await page.keyboard.press('Escape');await expect(button).toBeFocused();await expect(page.locator('#selectionActions')).toBeHidden();await button.click();await page.getByRole('menuitem',{name:'Create centerline',exact:true}).click();await page.getByLabel('Centerline method').selectOption('inset');await page.getByLabel('Centerline inset').fill('5');await page.getByLabel('Centerline inset').press('Tab');await expect(page.getByRole('button',{name:'Add centerline layer',exact:true})).toBeDisabled();await page.getByRole('button',{name:'Cancel',exact:true}).click();expect(await page.evaluate(()=>window.__gw.S.glyph.layers.length)).toBe(2);
});
test('a stale per-shape candidate cannot overwrite concurrent edits',async({page})=>{
 await setup(page);await page.locator('[data-tree-key="0:0"]').click({button:'right'});await actions(page);await page.getByRole('menuitem',{name:'Create centerline',exact:true}).click();await page.evaluate(()=>{const w=window.__gw;w.S.glyph.layers[1].node.x1=18;w.commit();w.refresh(true);});await page.getByRole('button',{name:'Add centerline layer',exact:true}).click();await expect(page.getByRole('dialog',{name:'Create centerline',exact:true})).toContainText('Artwork changed');expect(await page.evaluate(()=>window.__gw.S.glyph.layers.length)).toBe(2);expect(await page.evaluate(()=>window.__gw.S.glyph.layers[1].node.x1)).toBe(18);
});
