import {test,expect} from '@playwright/test';
const screen=async(page,x,y)=>page.evaluate(({x,y})=>{const c=document.querySelector('#canvas'),p=c.createSVGPoint();p.x=x;p.y=y;const q=p.matrixTransform(c.getScreenCTM());return {x:q.x,y:q.y};},{x,y});
const setup=async(page,node)=>{await page.goto('/');await page.waitForFunction(()=>window.__gw?.ready);await page.evaluate(async node=>{const w=window.__gw;await w.importLibraryText(JSON.stringify({name:'cleanup-fixture',weight:0.2,layers:[{id:'outline',paint:'stroke',node},{id:'untouched',paint:'stroke',node:{shape:'pen',pts:[{x:15,y:15},{x:16,y:15},{x:17,y:15}]}}]}),'cleanup.json');w.S.sel=[{l:0,p:[]}];w.setTool('direct');w.refresh(true);},node);};
test('Direct selection selects all anchors in the selected path, Cleanup simplifies only it and Undo/Redo persists',async({page})=>{
 const pts=Array.from({length:21},(_,i)=>({x:2+i/2,y:4+Math.sin(i/20)*2}));await setup(page,{shape:'pen',pts});
 await page.locator('#canvas').focus();await page.keyboard.press('ControlOrMeta+a');expect(await page.evaluate(()=>window.__gw.S.selectedAnchors.length)).toBe(21);
 await page.locator('#canvas').press('Shift+F10');await page.getByRole('menuitem',{name:'Actions',exact:true}).click();await expect(page.getByRole('menuitem',{name:'Cleanup',exact:true})).toBeVisible();await page.screenshot({path:'artifacts/anchor-cleanup-menu.png'});await page.getByRole('menuitem',{name:'Cleanup',exact:true}).click();
 const count=await page.evaluate(()=>window.__gw.S.glyph.layers[0].node.pts.length);expect(count).toBeLessThan(16);expect(await page.evaluate(()=>window.__gw.S.glyph.layers[1].node.pts.length)).toBe(3);await expect(page.locator('#status')).toContainText('Cleanup removed');
 await page.locator('#undoBtn').click();expect(await page.evaluate(()=>window.__gw.S.glyph.layers[0].node.pts)).toEqual(pts);await page.locator('#redoBtn').click();await page.evaluate(()=>window.__gw.flushSaves());await page.reload();await page.waitForFunction(()=>window.__gw?.ready);expect(await page.evaluate(()=>window.__gw.S.glyph.layers[0].node.pts.length)).toBe(count);
});
test('marquee selects a corner cluster, Merge to corner preserves exterior edges and remains procedurally roundable',async({page})=>{
 const pts=[{x:1,y:3},{x:3.8,y:3},{x:3.95,y:3.05},{x:4,y:3.2},{x:4,y:7}];await setup(page,{shape:'pen',pts});
 await page.locator('#canvas').scrollIntoViewIfNeeded();const start=await screen(page,3.6,2.5),end=await screen(page,4.3,3.3);await page.mouse.move(start.x,start.y);await page.mouse.down();await page.mouse.move(end.x,end.y);await expect(page.locator('#anchorMarquee')).toHaveCount(1);await page.mouse.up();expect(await page.evaluate(()=>window.__gw.S.selectedAnchors.map(a=>a.index))).toEqual([1,2,3]);
 const p=await screen(page,3.95,3.05);await page.mouse.click(p.x,p.y,{button:'right'});await page.getByRole('menuitem',{name:'Actions',exact:true}).click();await expect(page.locator('#itemMenu')).toContainText('3 selected anchors');await page.getByRole('menuitem',{name:'Merge to corner',exact:true}).click();
 const result=await page.evaluate(()=>window.__gw.S.glyph.layers[0].node.pts);expect(result).toHaveLength(3);expect(result[1].x).toBeCloseTo(4);expect(result[1].y).toBeCloseTo(3);expect(result[0]).toEqual(pts[0]);expect(result[2]).toEqual(pts[4]);expect(await page.evaluate(()=>window.__gw.S.selectedAnchors.map(a=>a.index))).toEqual([1]);
 await page.screenshot({path:'artifacts/anchor-corner-merged.png'});await page.locator('#undoBtn').click();expect(await page.evaluate(()=>window.__gw.S.glyph.layers[0].node.pts)).toEqual(pts);await page.locator('#redoBtn').click();
 const before=await page.evaluate(()=>window.__gw.core.resolve(window.__gw.S.glyph)[0].d);await page.locator('#setRoundingEnabled').check();const after=await page.evaluate(()=>window.__gw.core.resolve(window.__gw.S.glyph)[0].d);expect(after).not.toBe(before);
});
test('area split control supports lasso and polygon, Shift add, Alt subtract, keyboard dismissal and anchor Delete',async({page})=>{
 await setup(page,{shape:'pen',pts:[{x:2,y:4},{x:4,y:4},{x:6,y:4},{x:8,y:4},{x:10,y:4}]});
 const drag=async(a,b,modifier)=>{await page.locator('#canvas').scrollIntoViewIfNeeded();if(modifier)await page.keyboard.down(modifier);const p=await screen(page,...a),q=await screen(page,...b);await page.mouse.move(p.x,p.y);await page.mouse.down();await page.mouse.move(q.x,q.y,{steps:8});await page.mouse.up();if(modifier)await page.keyboard.up(modifier);};
 await drag([1.5,3],[4.5,5]);expect(await page.evaluate(()=>window.__gw.S.selectedAnchors.map(a=>a.index))).toEqual([0,1]);
 await drag([5.5,3],[6.5,5],'Shift');expect(await page.evaluate(()=>window.__gw.S.selectedAnchors.map(a=>a.index))).toEqual([0,1,2]);
 await drag([1.5,3],[2.5,5],'Alt');expect(await page.evaluate(()=>window.__gw.S.selectedAnchors.map(a=>a.index))).toEqual([1,2]);
 await page.locator('#areaSelectToggle').click();await expect(page.getByRole('menu',{name:'Area selection tools',exact:true})).toBeVisible();await page.keyboard.press('Escape');await expect(page.locator('#areaSelectToggle')).toBeFocused();
 await page.locator('#areaSelectToggle').click();await page.getByRole('menuitemradio',{name:'Lasso',exact:true}).click();await expect(page.locator('#areaSelectBtn')).toHaveAccessibleName('Lasso selection');await expect(page.locator('#areaSelectBtn')).toHaveAttribute('aria-pressed','true');
 await page.locator('#canvas').scrollIntoViewIfNeeded();const loop=[[7.5,3],[10.5,3],[10.5,5],[7.5,5],[7.5,3]].map(p=>p);const first=await screen(page,...loop[0]);await page.mouse.move(first.x,first.y);await page.mouse.down();for(const xy of loop.slice(1)){const p=await screen(page,...xy);await page.mouse.move(p.x,p.y,{steps:4});}await page.mouse.up();expect(await page.evaluate(()=>window.__gw.S.selectedAnchors.map(a=>a.index))).toEqual([3,4]);await expect(page.locator('#gSel [data-anchor="3"]')).toHaveAttribute('fill','var(--sel)');
 await page.locator('#areaSelectToggle').click();await page.getByRole('menuitemradio',{name:'Polygon lasso',exact:true}).click();await page.locator('#canvas').scrollIntoViewIfNeeded();
 for(const xy of [[3.5,3],[6.5,3],[6.5,5],[3.5,5]]){const p=await screen(page,...xy);await page.mouse.click(p.x,p.y);}await page.locator('#canvas').press('Enter');expect(await page.evaluate(()=>window.__gw.S.selectedAnchors.map(a=>a.index))).toEqual([1,2]);
 await page.locator('#areaSelectToggle').scrollIntoViewIfNeeded();await page.locator('#areaSelectToggle').click();await page.screenshot({path:'artifacts/area-selection-tools.png'});await page.keyboard.press('Escape');await page.locator('#canvas').press('Delete');expect(await page.evaluate(()=>window.__gw.S.glyph.layers.length)).toBe(2);expect(await page.evaluate(()=>window.__gw.S.glyph.layers[0].node.pts.length)).toBe(3);await page.locator('#undoBtn').click();expect(await page.evaluate(()=>window.__gw.S.glyph.layers[0].node.pts.length)).toBe(5);
});
test('area tools explicitly targeting objects select objects and polygon cancellation does not mutate artwork',async({page})=>{
 await setup(page,{shape:'pen',pts:[{x:2,y:4},{x:4,y:4},{x:6,y:4}]});await page.locator('[data-tool="select"]').click();await page.locator('#areaSelectToggle').click();await page.getByRole('menuitemradio',{name:'Select objects',exact:true}).click();
 await page.locator('#canvas').scrollIntoViewIfNeeded();const a=await screen(page,1,3),b=await screen(page,7,5);await page.mouse.move(a.x,a.y);await page.mouse.down();await page.mouse.move(b.x,b.y);await page.mouse.up();expect(await page.evaluate(()=>window.__gw.S.sel)).toEqual([{l:0,p:[]}]);expect(await page.evaluate(()=>window.__gw.S.selectedAnchors.length)).toBe(0);
 const before=await page.evaluate(()=>JSON.stringify(window.__gw.S.glyph));await page.locator('#areaSelectToggle').click();await page.getByRole('menuitemradio',{name:'Polygon lasso',exact:true}).click();await page.locator('#canvas').scrollIntoViewIfNeeded();for(const xy of [[14,14],[18,14]]){const p=await screen(page,...xy);await page.mouse.click(p.x,p.y);}await page.locator('#canvas').press('Escape');await expect(page.locator('#anchorMarquee')).toHaveCount(0);expect(await page.evaluate(()=>JSON.stringify(window.__gw.S.glyph))).toBe(before);
 await page.locator('#canvas').press('Escape');for(const xy of [[14,14],[18,14]]){const p=await screen(page,...xy);await page.mouse.click(p.x,p.y);}await page.evaluate(()=>window.__gw.loadGlyph(0));await expect(page.locator('#anchorMarquee')).toHaveCount(0);
 await page.reload();await page.waitForFunction(()=>window.__gw?.ready);await expect(page.locator('#areaSelectBtn')).toHaveAccessibleName('Polygon lasso selection');
});
