import {test,expect} from '@playwright/test';import {readFile} from 'node:fs/promises';import {unzipSync,strFromU8} from 'fflate';
test('SVG design-system color mappings export with fallbacks and persist; PNG and menu-bar outputs stay resolved',async({page})=>{
 await page.goto('/');await page.waitForFunction(()=>window.__gw?.ready);await page.locator('#libraryColorMode').selectOption('multicolor');await page.locator('#libraryUseColorTokens').check();await page.locator('#libraryFillToken').fill('--ds-icon-fill');await page.locator('#libraryFillToken').press('Tab');await page.locator('#libraryStrokeToken').fill('--ds-icon-stroke');await page.locator('#libraryStrokeToken').press('Tab');
 await page.locator('#expBaked').click();await expect(page.locator('#ioText')).toHaveValue(/var\(--ds-icon-stroke, #1d2430\)/);await expect(page.locator('#gLayers')).not.toContainText('var(--ds-icon-stroke');
 const mapping=await page.evaluate(svg=>{const host=document.createElement('div');host.innerHTML=svg;document.body.appendChild(host);const path=host.querySelector('path[stroke]'),fallback=getComputedStyle(path).stroke;host.style.setProperty('--ds-icon-stroke','#ff0000');const mapped=getComputedStyle(path).stroke;host.remove();return {fallback,mapped};},await page.locator('#ioText').inputValue());expect(mapping).toEqual({fallback:'rgb(29, 36, 48)',mapped:'rgb(255, 0, 0)'});
 await page.locator('.export-options > summary').click();const promise=page.waitForEvent('download');await page.locator('#expAll').click();const files=unzipSync(await readFile(await(await promise).path()));expect(Object.entries(files).some(([name,bytes])=>name.endsWith('.svg')&&strFromU8(bytes).includes('var(--ds-icon-stroke'))).toBe(true);
 const pngPromise=page.waitForEvent('download');await page.locator('#downloadPng').click();const png=await readFile(await(await pngPromise).path());const sharp=(await import('sharp')).default;const {data,info}=await sharp(png).ensureAlpha().raw().toBuffer({resolveWithObject:true});expect(Array.from({length:info.width*info.height},(_,i)=>i*4).some(i=>data[i+3]>200&&data[i]===29&&data[i+1]===36&&data[i+2]===48)).toBe(true);await page.reload();await page.waitForFunction(()=>window.__gw?.ready);await expect(page.locator('#libraryStrokeToken')).toHaveValue('--ds-icon-stroke');await expect(page.locator('#libraryUseColorTokens')).toBeChecked();
 await page.locator('#libraryOutputProfile').selectOption('menu-bar');await page.locator('#expBaked').click();await expect(page.locator('#ioText')).not.toHaveValue(/var\(--ds-icon/);await expect(page.locator('#ioText')).toHaveValue(/#000000/);
 const before=await page.locator('#libraryStrokeToken').inputValue();await page.locator('#libraryStrokeToken').fill('red" onload="alert(1)');await page.locator('#libraryStrokeToken').press('Tab');await expect(page.locator('#libraryStrokeToken')).toHaveValue(before);await expect(page.locator('#status')).toContainText('CSS custom property names');
});
