import {test,expect} from '@playwright/test';
const ready=async page=>{await page.goto('/');await page.waitForFunction(()=>window.__gw?.ready);};
const bell={name:'bell',weight:1.2,symmetry:{mirror:'x',rotate:1,axis:{x:12,y:12,angle:0}},layers:[{id:'bell',name:'Bell',paint:'stroke',node:{name:'Half bell',shape:'pen',pts:[{x:12,y:4},{x:8,y:7},{x:7,y:17},{x:12,y:17}],closed:false}}]};
const target={name:'silence-alarms',symmetry:{mirror:'xy',rotate:2},layers:[{id:'slash',name:'Slash',paint:'stroke',symmetry:false,node:{shape:'line',x1:4,y1:4,x2:20,y2:20}}]};
async function setup(page){await ready(page);await page.evaluate(async glyphs=>{await window.__gw.importLibraryText(JSON.stringify(glyphs),'bells.json','replace');},[bell,target]);}
test('right-click creates a complete mirrored Bell; independent Components section inserts it into Silence alarms and edits propagate with Undo/reload',async({page})=>{
  await setup(page);const before=await page.evaluate(()=>window.__gw.core.resolve(window.__gw.S.glyph)[0].d);
  const point=await page.evaluate(()=>{const c=document.querySelector('#canvas'),p=c.createSVGPoint();p.x=7.4;p.y=13;const q=p.matrixTransform(c.getScreenCTM());return{x:q.x,y:q.y};});
  await page.mouse.click(point.x,point.y,{button:'right'});await page.getByRole('menuitem',{name:'Actions',exact:true}).click();page.once('dialog',d=>d.accept('Bell'));await page.getByRole('menuitem',{name:'Create component',exact:true}).click();
  await expect(page.locator('#componentsCount')).toHaveText('1');expect(await page.evaluate(()=>document.querySelector('.library-panel').contains(document.querySelector('#componentsPanel')))).toBe(false);
  expect(await page.evaluate(()=>window.__gw.core.resolve(window.__gw.S.glyph)[0].d)).toBe(before);expect(await page.evaluate(()=>window.__gw.S.glyph.layers[0].symmetry)).toBe(false);
  await page.evaluate(()=>window.__gw.loadGlyph(1));await page.getByRole('button',{name:'Insert Bell into current icon',exact:true}).click();
  expect(await page.evaluate(()=>window.__gw.core.resolve(window.__gw.S.glyph)[1].d)).toBe(before);await expect(page.getByRole('button',{name:'Edit component Bell, 2 instances',exact:true})).toBeVisible();
  await page.evaluate(()=>{const w=window.__gw;w.S.glyph.layers[1].node.children[0].pts[1].x=9;w.commit();w.refresh(true);});expect(await page.evaluate(()=>window.__gw.S.lib[0].layers[0].node.children[0].pts[1].x)).toBe(9);
  await page.locator('#undoBtn').click();expect(await page.evaluate(()=>window.__gw.S.lib[0].layers[0].node.children[0].pts[1].x)).toBe(8);await page.locator('#redoBtn').click();await page.evaluate(()=>window.__gw.flushSaves());await page.reload();await page.waitForFunction(()=>window.__gw?.ready);await expect(page.getByRole('button',{name:'Edit component Bell, 2 instances',exact:true})).toBeVisible();await page.locator('#expJson').click();const doc=JSON.parse(await page.locator('#ioText').inputValue());expect(doc.components[0].node.symmetry.mirror).toBe('x');
});
test('anchor and Layers context menus expose creation; linked descendants cannot create nested components',async({page})=>{
  await setup(page);await page.evaluate(()=>{const w=window.__gw;w.setTool('direct');w.S.sel=[{l:0,p:[]}];w.S.anchor=1;w.S.selectedAnchors=[{selection:{l:0,p:[]},index:1}];w.refresh(true);});await page.locator('#canvas').focus();await page.keyboard.press('Shift+F10');await page.getByRole('menuitem',{name:'Actions',exact:true}).click();page.once('dialog',d=>d.accept('Bell'));await page.getByRole('menuitem',{name:'Create component',exact:true}).click();
  await page.locator('#undoBtn').click();await expect(page.locator('#componentsCount')).toHaveText('0');const row=page.locator('[data-tree-key="0:"]');await row.click({button:'right'});await page.getByRole('menuitem',{name:'Actions',exact:true}).click();page.once('dialog',d=>d.accept('Bell'));await page.getByRole('menuitem',{name:'Create component',exact:true}).click();await page.locator('#canvas').focus();await page.keyboard.press('Shift+F10');await page.getByRole('menuitem',{name:'Actions',exact:true}).click();await expect(page.getByRole('menuitem',{name:'Create component',exact:true})).toHaveCount(0);
});
test('icon thickness persists independently of library thickness across switching, Undo, reload and SVG output',async({page})=>{
  await setup(page);await page.locator('#setThicknessEnabled').check();await page.locator('#setThickness').fill('1.2');await page.locator('#setThickness').press('Tab');await page.locator('#iconThicknessOverride').check();await page.locator('#iconThickness').fill('2.4');await page.locator('#iconThickness').press('Tab');await page.locator('#setThickness').fill('1.8');await page.locator('#setThickness').press('Tab');
  expect(await page.evaluate(()=>window.__gw.S.glyph.strokeOverride)).toBe(2.4);await expect(page.locator('#gLayers path').first()).toHaveAttribute('stroke-width','2.4');await page.evaluate(()=>window.__gw.loadGlyph(1));await expect(page.locator('#gLayers path').first()).toHaveAttribute('stroke-width','1.8');await page.evaluate(()=>window.__gw.loadGlyph(0));await expect(page.locator('#iconThickness')).toHaveValue('2.4');await page.locator('#iconThicknessOverride').uncheck();await expect(page.locator('#gLayers path').first()).toHaveAttribute('stroke-width','1.8');await page.locator('#undoBtn').click();await expect(page.locator('#iconThicknessOverride')).toBeChecked();await expect(page.locator('#gLayers path').first()).toHaveAttribute('stroke-width','2.4');await page.evaluate(()=>window.__gw.flushSaves());await page.reload();await page.waitForFunction(()=>window.__gw?.ready);await page.locator('#expBaked').click();expect(await page.locator('#ioText').inputValue()).toContain('stroke-width="2.4"');
});
