import {test,expect} from '@playwright/test';
const ready=async page=>{await page.goto('/');await page.waitForFunction(()=>window.__gw?.ready);};
const deleteThree=async page=>{const tiles=page.locator('.lib-item');await tiles.nth(0).click();await tiles.nth(2).click({modifiers:['Shift']});await page.locator('#deleteIconsBtn').click();await expect(tiles).toHaveCount(1);};
const choose=async(page,name)=>page.locator('.deleted-icon-card').filter({hasText:name}).getByRole('checkbox').check();
test('deleted review restores only checked items and preserves remaining trash, edits and originals after reload',async({page})=>{
 const errors=[];page.on('pageerror',error=>errors.push(error.message));await ready(page);
 await page.locator('#iconDescription').fill('Edited before deletion');await page.locator('#iconDescription').press('Tab');
 const before=await page.evaluate(()=>window.__gw.S.lib.slice(0,3).map(glyph=>({glyph:structuredClone(glyph),original:structuredClone(window.__gw.ORIG.get(glyph.name))})));
 await deleteThree(page);await page.locator('#restoreIconsBtn').click();await expect(page.locator('.stage')).toBeHidden();await expect(page.locator('#groupReview')).toHaveAccessibleName(/Deleted icons/);await expect(page.locator('.deleted-icon-card')).toHaveCount(3);await expect(page.locator('.deleted-icon-card svg')).toHaveCount(3);await expect(page.locator('#restoreSelectedIconsBtn')).toBeDisabled();await expect(page.locator('.lib-item')).toHaveCount(1);await page.screenshot({path:'artifacts/deleted-icons-review.png',fullPage:true});
 await choose(page,before[0].glyph.name);await expect(page.locator('.deleted-icon-card.is-selected')).toHaveCount(1);await page.locator('#restoreSelectedIconsBtn').click();await expect(page.locator('.lib-item')).toHaveCount(2);await expect(page.locator('.deleted-icon-card')).toHaveCount(2);await expect(page.locator('#restoreIconsBtn')).toHaveText('Restore deleted (2)');
 expect(await page.evaluate(name=>window.__gw.S.lib.find(g=>g.name===name),before[0].glyph.name)).toEqual(before[0].glyph);
 await page.reload();await page.waitForFunction(()=>window.__gw?.ready);await expect(page.locator('.lib-item')).toHaveCount(2);await page.locator('#restoreIconsBtn').click();await expect(page.locator('.deleted-icon-card')).toHaveCount(2);await expect(page.locator('#restoreSelectedIconsBtn')).toBeDisabled();
 // Choose a later trash entry: original mapping must follow selected entries, not trash indices.
 await choose(page,before[2].glyph.name);await page.locator('#restoreSelectedIconsBtn').click();await expect(page.locator('.lib-item')).toHaveCount(3);expect(await page.evaluate(name=>window.__gw.ORIG.get(name),before[2].glyph.name)).toEqual(before[2].original);await expect(page.locator('#restoreIconsBtn')).toHaveText('Restore deleted (1)');
 await page.getByRole('button',{name:'Back to drawing',exact:true}).click();await page.locator('.lib-item').filter({hasText:before[0].glyph.name}).click();await page.locator('#revertBtn').click();await expect(page.locator('#iconDescription')).toHaveValue('');expect(errors).toEqual([]);
});
test('Escape cancels without restoring, keyboard selection is scoped to the review, and all is explicit',async({page})=>{
 await ready(page);await deleteThree(page);await page.locator('#restoreIconsBtn').click();await page.locator('.deleted-icon-card input').first().focus();await page.keyboard.press('Space');await expect(page.locator('#deletedSelectionCount')).toHaveText('1 selected');await page.keyboard.press('Escape');await expect(page.locator('.stage')).toBeVisible();await expect(page.locator('.lib-item')).toHaveCount(1);await expect(page.locator('#restoreIconsBtn')).toBeFocused();
 await page.locator('#restoreIconsBtn').click();await page.getByRole('button',{name:'Review Ungrouped',exact:true}).click();await expect(page.locator('#groupReview')).toHaveAccessibleName('Group drawing review');await page.locator('#restoreIconsBtn').click();await expect(page.locator('#restoreSelectedIconsBtn')).toBeDisabled();await page.keyboard.press('Meta+a');await expect(page.locator('#deletedSelectionCount')).toHaveText('3 selected');await page.locator('#clearDeletedSelectionBtn').click();await expect(page.locator('#restoreSelectedIconsBtn')).toBeDisabled();await page.locator('#selectAllDeletedBtn').click();await page.locator('#restoreSelectedIconsBtn').click();await expect(page.locator('.lib-item')).toHaveCount(4);await expect(page.locator('.stage')).toBeVisible();await expect(page.locator('#restoreIconsBtn')).toBeDisabled();
});
test('duplicate deleted names can be selected independently and storage failure leaves trash intact',async({page})=>{
 await ready(page);const source=await page.evaluate(()=>structuredClone(window.__gw.S.lib[0]));
 await page.locator('.lib-item').first().click();await page.locator('#deleteIconsBtn').click();source.description='Second deleted copy';await page.locator('#ioText').fill(JSON.stringify(source));await page.locator('#importBtn').click();await page.locator('#confirmImportBtn').click();await page.locator('.lib-item').filter({hasText:source.name}).click();await page.locator('#deleteIconsBtn').click();await page.locator('#restoreIconsBtn').click();await expect(page.locator('.deleted-icon-card')).toHaveCount(2);await page.locator('.deleted-icon-card').nth(1).getByRole('checkbox').check();
 await page.evaluate(()=>{const transaction=IDBDatabase.prototype.transaction;IDBDatabase.prototype.transaction=function(names,mode,...args){if(mode==='readwrite'&&Array.from(names).includes('snapshots')&&Array.from(names).includes('edits'))throw new Error('Injected restore transaction failure');return transaction.call(this,names,mode,...args);};});
 await page.locator('#restoreSelectedIconsBtn').click();await expect(page.locator('#status')).toContainText('Injected restore transaction failure');await expect(page.locator('.lib-item')).toHaveCount(3);await expect(page.locator('.deleted-icon-card')).toHaveCount(2);await expect(page.locator('#restoreSelectedIconsBtn')).toBeEnabled();
 await page.reload();await page.waitForFunction(()=>window.__gw?.ready);await page.locator('#restoreIconsBtn').click();await page.locator('.deleted-icon-card').nth(1).getByRole('checkbox').check();await page.locator('#restoreSelectedIconsBtn').click();await expect(page.locator('.lib-item')).toHaveCount(4);expect(await page.evaluate(name=>window.__gw.S.lib.find(g=>g.name===name).description,source.name)).toBe('Second deleted copy');await expect(page.locator('.deleted-icon-card')).toHaveCount(1);
 await page.locator('.deleted-icon-card input').check();await page.locator('#restoreSelectedIconsBtn').click();await expect(page.locator('.lib-item')).toHaveCount(5);expect(await page.evaluate(name=>window.__gw.S.lib.find(g=>g.name===`${name}-2`).description,source.name)).toBeUndefined();
});
