import {test,expect} from '@playwright/test';
const glyph={name:'fusion-bars-outline',weight:1.2,layers:[{id:'bars',name:'Barcode bars',paint:'stroke',node:{name:'Neighboring bars',op:'union',children:[7,8.8,12].map((x,i)=>({name:`Bar ${i+1}`,shape:'line',x1:x,y1:4,x2:x,y2:20}))}}]};
async function setup(page){await page.goto('/');await page.waitForFunction(()=>window.__gw?.ready);await page.evaluate(async g=>window.__gw.importLibraryText(JSON.stringify([g]),'fusion.json','replace'),glyph);}
async function open(page,canvas=false){if(canvas){await page.evaluate(()=>{const w=window.__gw;w.S.sel=[{l:0,p:[]}];w.refresh(true);});await page.locator('#canvas').press('Shift+F10');}else await page.locator('[data-tree-key="0:"]').click({button:'right'});await page.getByRole('menuitem',{name:'Actions',exact:true}).click();await page.getByRole('menuitem',{name:'Fuse nearby strokes',exact:true}).click();}
test('Fusion Actions shows both variants, persists editable recipe and undo; layer width regenerates fill geometry',async({page})=>{
  const errors=[];page.on('pageerror',e=>errors.push(e.message));await setup(page);const before=await page.evaluate(()=>JSON.stringify(window.__gw.S.glyph.layers[0].node.children));await open(page);
  const dialog=page.getByRole('dialog',{name:'Fuse nearby strokes',exact:true});await expect(dialog).toContainText('2 area(s)');await expect(dialog.locator('.review-drawing svg')).toHaveCount(2);await dialog.screenshot({path:'artifacts/fusion-review.png'});
  await page.getByLabel('Fusion merge distance').fill('0.65');await page.getByLabel('Fusion merge distance').press('Tab');await expect(page.getByRole('button',{name:'Save fusion',exact:true})).toBeEnabled();await page.getByLabel('Fusion merge distance').fill('2.4');await page.getByLabel('Fusion merge distance').press('Tab');await expect(dialog).toContainText('1 area(s)');await page.getByRole('button',{name:'Save fusion',exact:true}).click();
  expect(await page.evaluate(()=>JSON.stringify(window.__gw.S.glyph.layers[0].node.children))).toBe(before);await expect(page.locator('#gLayers path')).toHaveCount(1);await expect(page.locator('#gLayers path')).not.toHaveAttribute('stroke-width');await expect(page.locator('#pvLight path').first()).not.toHaveAttribute('stroke');
  const first=await page.locator('#gLayers path').getAttribute('d');await page.locator('#wRange').evaluate(el=>{el.value='3';el.dispatchEvent(new Event('input',{bubbles:true}));});expect(await page.locator('#gLayers path').getAttribute('d')).not.toBe(first);await page.locator('#setThicknessEnabled').check();await page.locator('#setThickness').fill('2');await page.locator('#setThickness').press('Tab');expect(await page.locator('#gLayers path').getAttribute('d')).not.toBe(first);
  await page.evaluate(()=>window.__gw.flushSaves());await page.reload();await page.waitForFunction(()=>window.__gw?.ready);expect(await page.evaluate(()=>window.__gw.S.glyph.layers[0].node.fusion.distance)).toBe(2.4);
  await open(page,true);await page.getByLabel('Enable proximity fusion').uncheck();await page.getByRole('button',{name:'Save fusion',exact:true}).click();await expect(page.locator('#gLayers path[stroke-width]')).toHaveCount(1);await page.locator('#undoBtn').click();await expect(page.locator('#gLayers path')).not.toHaveAttribute('stroke-width');await page.locator('#redoBtn').click();await expect(page.locator('#gLayers path[stroke-width]')).toHaveCount(1);expect(errors).toEqual([]);
});
test('Cancel and invalid distance leave source untouched; stale review cannot overwrite edits; menu is unavailable for a leaf',async({page})=>{
  await setup(page);const before=await page.evaluate(()=>JSON.stringify(window.__gw.S.glyph));await open(page);await page.getByLabel('Fusion merge distance').fill('-1');await page.getByLabel('Fusion merge distance').press('Tab');await expect(page.getByRole('button',{name:'Save fusion',exact:true})).toBeDisabled();await page.getByRole('button',{name:'Cancel',exact:true}).click();expect(await page.evaluate(()=>JSON.stringify(window.__gw.S.glyph))).toBe(before);
  await open(page);await page.evaluate(()=>{const w=window.__gw;w.S.glyph.layers[0].node.children[0].x1=6;w.commit();w.refresh(true);});await page.getByRole('button',{name:'Save fusion',exact:true}).click();await expect(page.getByRole('dialog',{name:'Fuse nearby strokes',exact:true})).toContainText('Artwork changed');await page.getByRole('button',{name:'Cancel',exact:true}).click();
  await page.locator('[data-tree-key="0:0"]').click({button:'right'});await page.getByRole('menuitem',{name:'Actions',exact:true}).click();await expect(page.getByRole('menuitem',{name:'Fuse nearby strokes',exact:true})).toHaveCount(0);
});
test('fusion preview protects counters, allows explicit hole closing and accepts distances above one',async({page})=>{
  await setup(page);await page.evaluate(()=>{const w=window.__gw;w.S.glyph.layers[0].node.children=[{shape:'circle',cx:12,cy:12,r:4}];w.commit();w.refresh(true);});await open(page);await page.getByLabel('Fusion merge distance').fill('10');await page.getByLabel('Fusion merge distance').press('Tab');await expect(page.getByRole('dialog',{name:'Fuse nearby strokes',exact:true})).toContainText('holes 1 → 1');await page.getByLabel('Preserve existing holes').uncheck();await expect(page.getByRole('dialog',{name:'Fuse nearby strokes',exact:true})).toContainText('holes 1 → 0');await page.getByRole('button',{name:'Save fusion',exact:true}).click();expect(await page.evaluate(()=>window.__gw.S.glyph.layers[0].node.fusion.distance)).toBe(10);
});
test('incompatible Boolean edit retains source and can recover through Disable fusion',async({page})=>{
  const errors=[];page.on('pageerror',e=>errors.push(e.message));await setup(page);await open(page);await page.getByRole('button',{name:'Save fusion',exact:true}).click();
  await page.evaluate(()=>{const w=window.__gw;w.S.glyph.layers[0].node.op='compound';w.commit();w.refresh(true);});
  await page.locator('[data-tree-key="0:"]').click({button:'right'});await page.getByRole('menuitem',{name:'Actions',exact:true}).click();await page.getByRole('menuitem',{name:'Disable proximity fusion',exact:true}).click();
  expect(await page.evaluate(()=>window.__gw.S.resolved[0].error)).toBeNull();expect(await page.evaluate(()=>window.__gw.S.glyph.layers[0].node.children.length)).toBe(3);expect(errors).toEqual([]);
});
