import {test,expect} from '@playwright/test';
import {readFile} from 'node:fs/promises';
const setup=async page=>{await page.goto('/');await page.waitForFunction(()=>window.__gw?.ready);await page.evaluate(async()=>{const w=window.__gw;await w.importLibraryText(JSON.stringify([{name:'barcode-outline',weight:1.6,layers:[{id:'original',name:'Original bars',paint:'fill',visible:false,node:{shape:'rect',x:3,y:3,w:16,h:18}},...[2.4,1.2,2.4].map((width,i)=>({id:`bar-${i}`,name:`Bar ${i+1}`,paint:'stroke',strokeWidth:width,rounding:0,endRounding:.5,node:{shape:'line',x1:4+i*5,y1:4.8,x2:4+i*5,y2:19.2}}))]}]),'barcode.json','replace');});};
test('barcode solid/export previews preserve bars and approvals, report blockers, and match downloadable SVG',async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));await setup(page);
 await expect(page.locator('#solidPreview svg')).toHaveCount(1);await expect(page.locator('#solidPreview path')).toHaveCount(3);await expect(page.locator('#solidPreview path[stroke]')).toHaveCount(0);
 const overlap=await page.evaluate(async()=>{
   const raster=async svg=>{const url=URL.createObjectURL(new Blob([svg],{type:'image/svg+xml'}));try{const image=new Image();await new Promise((resolve,reject)=>{image.onload=resolve;image.onerror=reject;image.src=url;});const c=document.createElement('canvas');c.width=c.height=512;const context=c.getContext('2d');context.drawImage(image,0,0,512,512);return context.getImageData(0,0,512,512).data;}finally{URL.revokeObjectURL(url);}};
   const a=await raster(window.__gw.core.toSVG(window.__gw.S.glyph,{mode:'baked',mono:true})),b=await raster(document.querySelector('#solidPreview .variant-art').dataset.svg);let intersection=0,union=0;for(let i=3;i<a.length;i+=4){if(a[i]>127&&b[i]>127)intersection++;if(a[i]>127||b[i]>127)union++;}return intersection/union;
 });expect(overlap).toBeGreaterThan(.995);
 const source=await page.evaluate(()=>JSON.stringify(window.__gw.S.glyph.layers));
 await page.locator('#libraryVariant').selectOption('solid');await expect(page.locator('#exportPreviewStatus')).toContainText('Export blocked');await expect(page.locator('#exportPreview svg')).toHaveCount(0);
 await page.locator('#approvePreviewSolid').click();await expect(page.locator('#exportPreview svg')).toHaveCount(1);expect(await page.evaluate(()=>JSON.stringify(window.__gw.S.glyph.layers))).toBe(source);
 const download=page.waitForEvent('download');await page.locator('#downloadSvg').click();const file=await download,svg=await readFile(await file.path(),'utf8');expect(file.suggestedFilename()).toBe('barcode.svg');expect(await page.locator('#exportPreview .variant-art').getAttribute('data-svg')).toBe(svg);
 const matches=await page.evaluate(svg=>{const expected=new DOMParser().parseFromString(svg,'image/svg+xml').documentElement;return [...expected.querySelectorAll('path')].map(p=>p.getAttribute('d')).join('|')===[...document.querySelectorAll('#exportPreview path')].map(p=>p.getAttribute('d')).join('|');},svg);expect(matches).toBe(true);
 await page.locator('#libraryVariant').selectOption('both');await expect(page.locator('#exportPreview svg')).toHaveCount(2);await expect(page.locator('#exportPreview')).toContainText('barcode-outline.svg');await expect(page.locator('#exportPreview')).toContainText('barcode.svg');
 await page.evaluate(()=>{const w=window.__gw;w.S.sel=[{l:1,p:null}];w.refresh(true);});const before=await page.locator('#solidPreview').innerHTML();await page.getByLabel('layer stroke width',{exact:true}).fill('2');await page.getByLabel('layer stroke width',{exact:true}).press('Tab');expect(await page.locator('#solidPreview').innerHTML()).not.toBe(before);await expect(page.locator('#exportPreviewStatus')).toContainText('Export blocked');
 await page.locator('#undoBtn').click();await expect(page.locator('#exportPreview svg')).toHaveCount(2);await page.evaluate(()=>window.__gw.flushSaves());await page.reload();await page.waitForFunction(()=>window.__gw?.ready);await expect(page.locator('#exportPreview svg')).toHaveCount(2);expect(errors).toEqual([]);
});
test('blocked outline reconstruction remains blocked even with a drawable solid',async({page})=>{
 await setup(page);await page.evaluate(()=>{const w=window.__gw;w.S.glyph.variantFamily={canonical:'outline',status:'needs-review',reason:'Source must be redrawn'};w.commit();w.refresh(true);});await expect(page.locator('#approvePreviewSolid')).toBeDisabled();await page.locator('#libraryVariant').selectOption('solid');await expect(page.locator('#exportPreviewStatus')).toContainText('outline reconstruction');await expect(page.locator('#exportPreview svg')).toHaveCount(0);
});

test('barcode cutout box has separate corner rules; masked library ends can be applied directly',async({page})=>{
 await setup(page);await page.locator('#solidTreatment').selectOption('cutout');await expect(page.locator('#solidBoxSettings')).toBeVisible();await page.locator('#solidBoxFollowsRounding').uncheck();await page.getByLabel('Solid box corner radius',{exact:true}).fill('.8');await page.getByLabel('Solid box corner radius',{exact:true}).press('Tab');expect(await page.evaluate(()=>window.__gw.S.glyph.solidConstruction.cornerRounding)).toBe(.8);
 const shape=await page.locator('#solidPreview path').getAttribute('d');expect(await page.locator('#solidPreview path').count()).toBe(1);await page.locator('#libraryVariant').selectOption('solid');await page.locator('#approvePreviewSolid').click();await expect(page.locator('#exportPreview path')).toHaveAttribute('d',shape);
 await page.evaluate(()=>{const w=window.__gw;w.S.sel=[{l:1,p:[ ]}];w.S.glyph.layers[1].endRounding=0;w.commit();w.refresh(true);});await page.locator('#setEndRoundingEnabled').check();await page.locator('#setEndRounding').fill('.5');await page.locator('#setEndRounding').press('Tab');await expect(page.locator('#lineEndScopeNote')).toContainText('local end radius 0');const before=await page.locator('#solidPreview path').getAttribute('d');await page.locator('#useLibraryEndRounding').click();expect(await page.evaluate(()=>window.__gw.S.glyph.layers[1].endRounding)).toBeUndefined();await expect(page.locator('#lineEndScopeNote')).toBeHidden();expect(await page.locator('#solidPreview path').getAttribute('d')).not.toBe(before);expect(await page.evaluate(()=>window.__gw.S.glyph.layers[1].strokeWidth)).toBe(2.4);expect(await page.evaluate(()=>window.__gw.S.glyph.solidConstruction.cornerRounding)).toBe(.8);
 await page.evaluate(()=>window.__gw.flushSaves());await page.reload();await page.waitForFunction(()=>window.__gw?.ready);await expect(page.locator('#solidTreatment')).toHaveValue('cutout');await expect(page.getByLabel('Solid box corner radius',{exact:true})).toHaveValue('0.8');
});
