import paper from 'paper';
import {offset,offsetStroke} from 'paperjs-offset';
import {strokeWeight,layerStyleGlyph} from './stroke-weight.js';

const parse=d=>new paper.CompoundPath({pathData:d,insert:false});
const paths=item=>item.children||[item];
const merge=(a,b,op='unite')=>{if(!a)return b;const next=a[op](b,{insert:false});a.remove();b.remove();return next;};
export const fusionOn=node=>node.fusion?.enabled===true;
export function fusionGroups(node,path=[],ancestors=[]) {
  if(!node||node.hidden)return [];
  if(fusionOn(node))return [{node,path,ancestors}];
  return (node.children||[]).flatMap((child,i)=>fusionGroups(child,[...path,i],[...ancestors,node]));
}
export function fusionTarget(glyph,selection) {
  if(!selection || !glyph.layers[selection.l] || (glyph.layers[selection.l].paint||'stroke')!=='stroke')return null;
  const path=selection.p||[],ancestors=[];let node=glyph.layers[selection.l].node;
  for(const i of path){ancestors.push(node);node=node.children?.[i];if(!node)return null;}
  if(node.hidden||!node.children?.length||(node.op||'union')!=='union'||ancestors.some(n=>n.hidden||fusionOn(n)||(n.op||'union')!=='union'))return null;
  if((node.children||[]).some(n=>fusionGroups(n).length))return null;
  return {node,path,ancestors};
}
export function validateFusion(value) {
  if(!value || typeof value!=='object' || typeof value.enabled!=='boolean' || !Number.isFinite(value.distance) || value.distance<0 || typeof value.preserveCounters!=='boolean')throw Error('Invalid proximity fusion recipe');
}

export function fuseArea(original,recipe) {
  validateFusion(recipe);
  if(!original || Math.abs(original.area)<1e-8)throw Error('No stroke area to fuse');
  const source=original.clone({insert:false});source.reorient(true,true);
  const counters=paths(source).filter(p=>p.area<0).map(p=>{const c=p.clone({insert:false});c.clockwise=true;return c;});
  let result;
  try {
    if(recipe.distance===0)result=source.clone({insert:false});
    else {
      const grown=offset(source,recipe.distance/2,{join:'round',insert:false});
      try {if(!grown)throw Error('Fusion expansion collapsed');const united=grown.resolveCrossings();result=offset(united,-recipe.distance/2,{join:'round',insert:false});}
      finally{grown?.remove();}
      if(!result || Math.abs(result.area)<1e-8)throw Error('Fusion contracted to empty geometry');
      // Approximate offsets must never erase original ink.
      result=merge(result,source.clone({insert:false}));
    }
    if(recipe.preserveCounters)for(const counter of counters)result=merge(result,counter.clone({insert:false}),'subtract');
    if(!result || !Number.isFinite(result.area) || Math.abs(result.area)<1e-8 || paths(result).some(p=>p.segments.some(s=>![s.point.x,s.point.y,s.handleIn.x,s.handleIn.y,s.handleOut.x,s.handleOut.y].every(Number.isFinite))))throw Error('Fusion produced invalid geometry');
    result.reorient(true,true);
    return {item:result,beforeCounters:counters.length,afterCounters:paths(result).filter(p=>p.area<0).length,parts:paths(result).filter(p=>p.area>0).length};
  }catch(error){result?.remove();throw error;}
  finally{source.remove();counters.forEach(p=>p.remove());}
}

function expandedOpen(path,width,cap,join) {
  const p=path.clone({insert:false});
  if(cap==='square') {
    p.firstSegment.point=p.firstSegment.point.subtract(p.getTangentAt(0).normalize(width/2));
    p.lastSegment.point=p.lastSegment.point.add(p.getTangentAt(p.length).normalize(width/2));
  }
  try{return offsetStroke(p,width/2,{join,cap:cap==='round'?'round':'butt',insert:false});}finally{p.remove();}
}
// Procedural tip paths are generated by the same core used by SVG rendering.
function tipRegion(svg,width) {
  let result=null;
  for(const match of svg.matchAll(/transform="translate\(([-\d.e]+) ([-\d.e]+)\) rotate\(([-\d.e]+)\)"[^>]*><path d="([^"]+)"/g)) {
    const tip=parse(match[4]);tip.scale(width,new paper.Point(0,0));tip.rotate(Number(match[3]),new paper.Point(0,0));tip.translate([Number(match[1]),Number(match[2])]);result=merge(result,tip);
  }
  return result;
}
export function strokeArea(parts,width,styleFor,tipsFor) {
  let result=null;
  try{for(const part of parts){
    const source=parse(part.d),style=styleFor(part);
    try{for(const path of source.children){
      if(path.length<1e-8)continue;
      const region=path.closed?offsetStroke(path,width/2,{join:style.join,insert:false}):expandedOpen(path,width,style.cap,style.join);
      if(!region)throw Error('Stroke expansion failed');result=merge(result,region);
    }}finally{source.remove();}
    const tips=tipRegion(tipsFor(part),width);if(tips)result=merge(result,tips);
  }return result;}catch(error){result?.remove();throw error;}
}

// Freeze implicit pivots against the complete original group before isolating
// its members or hiding them in the residual branch.
function freezePivots(node,core) {
  const copy=structuredClone(node);
  if(copy.transform&&!copy.transform.origin){const geometry=core.evalNode({...node,transform:undefined}),items=[...(geometry.closed?[geometry.closed]:[]),...geometry.open];const b=items.reduce((b,p)=>b?b.unite(p.bounds):p.bounds.clone(),null);if(b)copy.transform.origin=[b.center.x,b.center.y];items.forEach(p=>p.remove());}
  copy.children=node.children?.map(n=>freezePivots(n,core));return copy;
}
const at=(node,path)=>path.reduce((n,i)=>n.children[i],node);
export function resolveFusionLayer(layer,glyph,layerIndex,raw,core,opts={}) {
  const groups=fusionGroups(layer.node);if(!groups.length||!raw.visible||(layer.paint||'stroke')!=='stroke')return raw;
  try {
    const frozen=freezePivots(layer.node,core),residual=structuredClone(frozen),parts=[],styled=layerStyleGlyph(glyph,layer),width=layer.strokeWidth??opts.weight??strokeWeight(glyph);
    for(const {node,path,ancestors} of groups) {
      validateFusion(node.fusion);
      if(!fusionTarget(glyph,{l:layerIndex,p:path}))throw Error('Nested or incompatible fusion group');
      if((node.op||'union')!=='union'||ancestors.some(n=>(n.op||'union')!=='union'))throw Error('Fusion groups need union ancestors');
      let isolated=at(frozen,path);at(residual,path).hidden=true;
      for(let i=path.length-1;i>=0;i--){const ancestor=at(frozen,path.slice(0,i));isolated={...ancestor,op:'union',children:[isolated]};}
      const source=core.resolve({...glyph,layers:[{...layer,node:isolated}]},{...opts,skipFusion:true})[0];if(source.error)throw Error(source.error);
      const area=strokeArea(source.parts,width,p=>core.strokeStyle(styled,opts,p.cap),p=>core.strokeTipsSVG(styled,p.d,{mode:'baked',weight:width,layerIndex}));
      let fused;try{fused=fuseArea(area,node.fusion);}finally{area?.remove();}
      try{parts.push({d:core.itemD(fused.item),cap:null,fusion:{recipe:structuredClone(node.fusion),sourceParts:source.parts,width,path,style:{cap:styled.strokeCap||opts.cap||'round',join:styled.strokeJoin||opts.join||'round'},beforeCounters:fused.beforeCounters,afterCounters:fused.afterCounters,parts:fused.parts}});}finally{fused.item.remove();}
    }
    const rest=core.resolve({...glyph,layers:[{...layer,node:residual}]},{...opts,skipFusion:true})[0];if(rest.error)throw Error(rest.error);
    return {...raw,parts:[...rest.parts,...parts],d:[rest.d,...parts.map(p=>p.d)].join('')};
  }catch(error){return {...raw,error:`Proximity fusion: ${error.message}`};}
}
